import os
import io
import zipfile
from flask import Flask, render_template, request, jsonify, send_file
import g4f

# Force g4f to use a better provider for reliability
from g4f.Provider import (
    Blackbox,
    ChatGptEs,
    FreeChatgpt,
    Liaobots
)

app = Flask(__name__)

# --- ROUTES ---

@app.route('/')
def index():
    # Templates folder lo unna index.html ni load chesthundhi
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate():
    data = request.json
    user_prompt = data.get('prompt')
    current_code = data.get('current_code', '')

    # AI context builder
    if current_code:
        # Edit cheyali ante patha code ni pampali
        full_message = f"Current Code:\n{current_code}\n\nUser Request: {user_prompt}\n\nUpdate the code and return only the FULL updated HTML/CSS/JS code."
    else:
        # Kotha app build cheyali ante
        full_message = f"Build a modern mobile-responsive website for: {user_prompt}. Use Tailwind CSS. Return only the full HTML code. No explanation."

    try:
        # Model selection: gpt-4o try chesthunnam ekkuva reliability kosam
        response = g4f.ChatCompletion.create(
            model=g4f.models.gpt_4o,
            messages=[{"role": "user", "content": full_message}],
            # Best providers ni prioritize chesthunnam
            provider=g4f.Provider.Blackbox, 
            stream=False,
        )

        if not response:
            return jsonify({"error": "AI response was empty"}), 500

        # AI response lo markdown code blocks (```html) unte remove cheyalii
        clean_code = response.replace("```html", "").replace("```", "").strip()
        
        return jsonify({"code": clean_code})

    except Exception as e:
        print(f"Server Error: {str(e)}")
        return jsonify({"error": "AI Busy. Please try again in a few seconds."}), 500

@app.route('/download-zip', methods=['POST'])
def download_zip():
    data = request.json
    code = data.get('code', '')
    
    if not code:
        return jsonify({"error": "No code to download"}), 400

    # Memory lo ZIP create chesthunnam
    memory_file = io.BytesIO()
    with zipfile.ZipFile(memory_file, 'w') as zf:
        zf.writestr('index.html', code)
        zf.writestr('Project_Info.txt', "Generated by Mahi Dev AI Builder.")
    
    memory_file.seek(0)
    return send_file(
        memory_file, 
        download_name='MahiDev_Project.zip', 
        as_attachment=True,
        mimetype='application/zip'
    )

# --- RENDER DEPLOYMENT SETTINGS ---

if __name__ == '__main__':
    # Render variables nundi PORT ni pick chesthundhi
    port = int(os.environ.get("PORT", 5000))
    # 0.0.0.0 host pettadam valla Render network ki access dorukuthundhi
    app.run(host='0.0.0.0', port=port)
