import os
import io
import zipfile
from flask import Flask, render_template, request, jsonify, send_file
import g4f

app = Flask(__name__)

# --- ROUTES ---

@app.route('/')
def index():
    # ఇది templates/index.html ఫైల్‌ని చూపిస్తుంది
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate():
    data = request.json
    user_prompt = data.get('prompt')
    current_code = data.get('current_code', '')

    # AI కి ఇచ్చే ఇన్స్ట్రక్షన్స్ (Lovable లాగా పని చేయడానికి)
    if current_code:
        # ఒకవేళ ఆల్రెడీ కోడ్ ఉంటే, దాన్ని మార్చమని అడగడం (Chat Edit)
        system_prompt = (
            f"You are a professional web developer. Here is the current HTML code:\n\n{current_code}\n\n"
            f"User wants to change: {user_prompt}\n\n"
            "Modify the code and return only the FULL updated HTML/Tailwind CSS code. "
            "Do not explain. No markdown backticks. Just raw HTML code."
        )
    else:
        # మొదటిసారి కొత్తగా క్రియేట్ చేయడం
        system_prompt = (
            f"Create a beautiful, modern, and mobile-responsive website for: {user_prompt}. "
            "Use Tailwind CSS via CDN. Include JavaScript if needed for functionality. "
            "Return only the full HTML code. No explanations. No markdown backticks."
        )

    try:
        # Free AI API (GPT-3.5)
        response = g4f.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": system_prompt}],
        )
        
        # ఒకవేళ AI పొరపాటున ```html ... ``` అని ఇస్తే వాటిని తీసేయడానికి
        clean_code = response.replace("```html", "").replace("```", "").strip()
        
        return jsonify({"code": clean_code})
    except Exception as e:
        print(f"Error: {str(e)}")
        return jsonify({"error": "AI response error. Try again."}), 500

@app.route('/download-zip', methods=['POST'])
def download_zip():
    data = request.json
    code = data.get('code', '')
    
    # మెమరీలో ZIP ఫైల్ క్రియేట్ చేయడం
    memory_file = io.BytesIO()
    with zipfile.ZipFile(memory_file, 'w') as zf:
        zf.writestr('index.html', code)
        zf.writestr('README.txt', "Generated by Mahi Dev AI - Lovable Clone")
    
    memory_file.seek(0)
    return send_file(
        memory_file, 
        download_name='MahiDev_Project.zip', 
        as_attachment=True,
        mimetype='application/zip'
    )

# --- RENDER DEPLOYMENT FIX ---

if __name__ == '__main__':
    # Render ఇచ్చే PORT ని ఆటోమేటిక్ గా తీసుకుంటుంది
    # లేకపోతే 5000 పోర్ట్ వాడుతుంది
    port = int(os.environ.get("PORT", 5000))
    # host='0.0.0.0' ఉండటం వల్ల బాహ్య ప్రపంచానికి వెబ్‌సైట్ కనిపిస్తుంది
    app.run(host='0.0.0.0', port=port)
