from flask import Flask, render_template, request, jsonify, send_file
import g4f
import io
import zipfile

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate():
    data = request.json
    prompt = data.get('prompt')
    
    # AI కి స్ట్రాంగ్ వార్నింగ్ ఇస్తున్నాం కేవలం కోడ్ మాత్రమే ఇవ్వమని
    system_prompt = (
        f"You are an expert mobile web developer. Build this app: {prompt}. "
        "IMPORTANT: Provide a SINGLE HTML file containing all CSS (Tailwind CDN) and JavaScript. "
        "Do NOT use markdown. Do NOT write explanations. Just raw HTML code."
    )
    
    try:
        # gpt-3.5-turbo లేదా gpt-4o వాడొచ్చు (g4f లో ఏది పనిచేస్తే అది)
        response = g4f.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": system_prompt}],
        )
        return jsonify({"code": response})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/download-zip', methods=['POST'])
def download_zip():
    data = request.json
    code = data.get('code', '')
    
    memory_file = io.BytesIO()
    with zipfile.ZipFile(memory_file, 'w') as zf:
        zf.writestr('index.html', code)
        zf.writestr('README.txt', "Generated by Mahi Dev AI")
    
    memory_file.seek(0)
    return send_file(memory_file, download_name='MahiDev_Project.zip', as_attachment=True)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
